# Generated by Django 4.0.4 on 2022-07-12 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unique for the period', primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('typ', models.CharField(help_text='Cuatrimestre, examanes...', max_length=100)),
            ],
        ),
    ]
