# Generated by Django 4.0.4 on 2022-05-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('num_pc', models.BigIntegerField(default=0)),
                ('s_o', models.CharField(max_length=20)),
                ('num_class', models.CharField(max_length=10)),
                ('capacity', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
