# Generated by Django 4.0.4 on 2022-07-12 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('request_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unique for the slot', primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('schedule', models.DateField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request_class.requestclass')),
            ],
        ),
    ]
