# Generated by Django 4.0.4 on 2022-07-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='day',
        ),
        migrations.AlterField(
            model_name='slot',
            name='schedule',
            field=models.CharField(max_length=20),
        ),
    ]
