# Generated by Django 4.0.6 on 2022-08-17 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('small_group', '0001_initial'),
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestClass',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, help_text='ID unique for the request', primary_key=True, serialize=False)),
                ('code', models.IntegerField(default=0)),
                ('typ', models.CharField(max_length=100)),
                ('preference', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('specification', models.CharField(max_length=100)),
                ('num_alum', models.IntegerField(default=0)),
                ('s_o', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('alternative_day', models.CharField(max_length=50)),
                ('imparter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_teacher', to='teacher.teacher')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.period')),
                ('s_g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_group.smallgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_sender', to='teacher.teacher')),
            ],
        ),
    ]
