# Generated by Django 4.0.4 on 2022-07-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestclass',
            name='imparter',
        ),
        migrations.RemoveField(
            model_name='requestclass',
            name='sender',
        ),
    ]
