# Generated by Django 4.0.4 on 2022-07-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('request_class', '0002_remove_requestclass_imparter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestclass',
            name='imparter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_teacher', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='requestclass',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_sender', to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
