# Generated by Django 4.0.4 on 2022-07-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_class', '0003_requestclass_imparter_requestclass_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestclass',
            old_name='id',
            new_name='code',
        ),
    ]
