# Generated by Django 4.0.6 on 2022-08-17 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmallGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unique for the small group', primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=5)),
                ('letter', models.CharField(max_length=1)),
                ('code', models.CharField(max_length=4)),
                ('degree', models.CharField(max_length=100)),
            ],
        ),
    ]
